#!/usr/bin/env python3
"""Split support/index.php tab panels into HTML files for the React app."""
from __future__ import annotations

import re
from pathlib import Path

SRC = Path("/var/www/support/index.php")
OUT = Path("/var/www/support-ui/src/docs/panels")

SKIP = {"commands"}  # built in React from the commands API


def extract_panels(text: str) -> dict[str, str]:
    panels: dict[str, str] = {}
    marker = '<div class="sp-tab-panel sp-doc-content" data-panel="'
    i = 0
    while True:
        start = text.find(marker, i)
        if start < 0:
            break
        id_start = start + len(marker)
        id_end = text.find('">', id_start)
        panel_id = text[id_start:id_end]
        inner_start = id_end + 2
        pos = inner_start
        depth = 1
        while pos < len(text) and depth:
            nxt_open = text.find("<div", pos)
            nxt_close = text.find("</div>", pos)
            if nxt_close < 0:
                break
            if nxt_open >= 0 and nxt_open < nxt_close:
                depth += 1
                pos = nxt_open + 4
            else:
                depth -= 1
                if depth == 0:
                    panels[panel_id] = text[inner_start:nxt_close]
                    i = nxt_close + 6
                    break
                pos = nxt_close + 6
        else:
            break
    return panels


def strip_php(html: str) -> str:
    html = re.sub(r"<\?php.*?\?>", "", html, flags=re.S)
    html = re.sub(r"<script>\s*\(function \(\) \{.*?currentVoice.*?\}\)\(\);\s*</script>", "", html, flags=re.S)
    return html.strip() + "\n"


def replace_tts_loops(html: str) -> str:
    html = re.sub(
        r'<div style="display:grid;grid-template-columns:repeat\(auto-fit,minmax\(240px,1fr\)\);gap:1rem;margin-top:1rem;">\s*<\?php foreach \(\$ttsVoices.*?</div>\s*<\?php endforeach; \?>\s*</div>',
        '<div id="react-tts-normal" style="display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:1rem;margin-top:1rem;"></div>',
        html,
        count=1,
        flags=re.S,
    )
    html = re.sub(
        r"<\?php if \(\$expressiveTtsVoices\): \?>.*?<\?php endif; \?>",
        '<div id="react-tts-expressive"></div>',
        html,
        count=1,
        flags=re.S,
    )
    return html


def main() -> None:
    text = SRC.read_text(encoding="utf-8")
    OUT.mkdir(parents=True, exist_ok=True)
    panels = extract_panels(text)
    written = []
    for pid, inner in panels.items():
        if pid in SKIP:
            continue
        html = inner
        if pid == "tts":
            html = replace_tts_loops(html)
        html = strip_php(html)
        (OUT / f"{pid}.html").write_text(html, encoding="utf-8")
        written.append(pid)

    barrel = ["// Auto-generated by scripts/extract-docs.py — do not edit by hand.\n"]
    imports = []
    for pid in written:
        key = pid.replace("-", "_")
        imports.append(f"import {key} from './panels/{pid}.html?raw'")
    barrel.extend(imports)
    barrel.append("")
    barrel.append("export const DOC_PANELS: Record<string, string> = {")
    for pid in written:
        key = pid.replace("-", "_")
        barrel.append(f"  '{pid}': {key},")
    barrel.append("}")
    barrel.append("")
    (OUT.parent / "panels.ts").write_text("\n".join(barrel) + "\n", encoding="utf-8")
    print("wrote", ", ".join(written))


if __name__ == "__main__":
    main()
