// Auto-generated by scripts/extract-docs.py — do not edit by hand.

import setup from './panels/setup.html?raw'
import features from './panels/features.html?raw'
import spotify from './panels/spotify.html?raw'
import tts from './panels/tts.html?raw'
import obs_audio from './panels/obs-audio.html?raw'
import variables from './panels/variables.html?raw'
import twitch_channel_points from './panels/twitch-channel-points.html?raw'
import api from './panels/api.html?raw'
import run_yourself from './panels/run-yourself.html?raw'
import faq from './panels/faq.html?raw'
import troubleshooting from './panels/troubleshooting.html?raw'

export const DOC_PANELS: Record<string, string> = {
  'setup': setup,
  'features': features,
  'spotify': spotify,
  'tts': tts,
  'obs-audio': obs_audio,
  'variables': variables,
  'twitch-channel-points': twitch_channel_points,
  'api': api,
  'run-yourself': run_yourself,
  'faq': faq,
  'troubleshooting': troubleshooting,
}

