<?php
return [
    'description' => 'Baseline: website system tables (known_bots, custom_webhooks, feedback, system_metrics, freestuff_games)',
    'up' => [
        "CREATE TABLE IF NOT EXISTS known_bots (
            id INT NOT NULL AUTO_INCREMENT,
            bot_login VARCHAR(50) NOT NULL,
            is_active TINYINT(1) NOT NULL DEFAULT 1,
            added_by VARCHAR(50) DEFAULT NULL,
            notes VARCHAR(255) DEFAULT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (id),
            UNIQUE KEY uniq_bot_login (bot_login)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "INSERT IGNORE INTO known_bots (bot_login, added_by) VALUES
            ('0_applejuice_0','system'),('8hvdes','system'),('anotherttvviewer','system'),
            ('blerp','system'),('botofthespecter','system'),('coebot','system'),
            ('commanderroot','system'),('communityshowcase','system'),('creatisbot','system'),
            ('deepbot','system'),('electricallongboard','system'),('feardn','system'),
            ('fossabot','system'),('host_giveaway','system'),('icewaslit','system'),
            ('kofistreambot','system'),('lattemotte','system'),('logviewer','system'),
            ('lurxx','system'),('moobot','system'),('n3td3v','system'),('nightbot','system'),
            ('own3d','system'),('p0lizei_','system'),('phantombot','system'),('pretzelrocks','system'),
            ('restreambot','system'),('sery_bot','system'),('songlistbot','system'),
            ('soundalerts','system'),('streamelements','system'),('streamfahrer','system'),
            ('streamlabs','system'),('streamlootsbot','system'),('streamstickers','system'),
            ('tangiabot','system'),('the_marlchurch','system'),('twitchprimereminder','system'),
            ('v_and_k','system'),('vivbot','system'),('wizebot','system')",
        "CREATE TABLE IF NOT EXISTS custom_webhooks (
            id INT AUTO_INCREMENT PRIMARY KEY,
            slug VARCHAR(64) NOT NULL UNIQUE,
            name VARCHAR(100) NOT NULL,
            service VARCHAR(64) NOT NULL,
            event_name VARCHAR(64) NOT NULL,
            scope ENUM('channel','global') NOT NULL DEFAULT 'channel',
            target_username VARCHAR(255) NULL,
            verify_mode ENUM('none','secret','hmac') NOT NULL DEFAULT 'secret',
            secret VARCHAR(255) NULL,
            secret_header VARCHAR(64) NOT NULL DEFAULT 'X-Webhook-Secret',
            enabled TINYINT(1) NOT NULL DEFAULT 1,
            created_by VARCHAR(255) NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            last_received_at TIMESTAMP NULL DEFAULT NULL,
            received_count INT NOT NULL DEFAULT 0,
            INDEX idx_enabled (enabled)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS feedback (
            id INT AUTO_INCREMENT PRIMARY KEY,
            twitch_user_id VARCHAR(64),
            display_name VARCHAR(255),
            message TEXT,
            is_bug_report TINYINT(1) DEFAULT 0,
            bug_category VARCHAR(100),
            severity VARCHAR(50),
            steps_to_reproduce TEXT,
            expected_behavior TEXT,
            actual_behavior TEXT,
            browser_info VARCHAR(500),
            error_message TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS system_metrics (
            id INT AUTO_INCREMENT PRIMARY KEY,
            server_name VARCHAR(255) NOT NULL,
            cpu_percent FLOAT,
            ram_percent FLOAT,
            ram_used FLOAT,
            ram_total FLOAT,
            disk_percent FLOAT,
            disk_used FLOAT,
            disk_total FLOAT,
            net_sent FLOAT,
            net_recv FLOAT,
            last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY unique_server (server_name)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS freestuff_games (
            id INT AUTO_INCREMENT PRIMARY KEY,
            game_id VARCHAR(255),
            game_title VARCHAR(500),
            game_org VARCHAR(255),
            game_thumbnail TEXT,
            game_url TEXT,
            game_description TEXT,
            game_price VARCHAR(50),
            received_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            INDEX idx_received_at (received_at)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
    ],
    'down' => [],
];
