export type Helpline = { country: string; name: string; number: string }

export const HELPLINES: Helpline[] = [
  { country: 'Australia', name: 'Lifeline', number: '13 11 14' },
  { country: 'United States', name: 'SAMHSA Helpline', number: '800-662-4357' },
  { country: 'Canada', name: 'Wellness Together Canada', number: '1-866-585-0445' },
  { country: 'United Kingdom', name: 'Samaritans', number: '116 123' },
  { country: 'Ireland', name: 'Samaritans', number: '116 123' },
  { country: 'France', name: 'SOS Amitié', number: '09 72 39 40 50' },
  { country: 'Germany', name: 'TelefonSeelsorge', number: '0800 111 0111' },
  { country: 'Spain', name: 'Teléfono de la Esperanza', number: '717 003 717' },
  { country: 'Italy', name: 'Telefono Amico', number: '199 284 284' },
  { country: 'Netherlands', name: 'De Luisterlijn', number: '0900 0767' },
  { country: 'Belgium', name: 'Zelfmoordlijn', number: '1813' },
  { country: 'Sweden', name: 'Jourhavande medmänniska', number: '08-702 16 80' },
  { country: 'Denmark', name: 'Livslinien', number: '70 201 201' },
  { country: 'Norway', name: 'Mental Helse', number: '116 123' },
  { country: 'Finland', name: 'MIELI Crisis Helpline', number: '09 2525 0111' },
  { country: 'Switzerland', name: 'La Main Tendue', number: '143' },
  { country: 'Poland', name: 'Befrienders', number: '22 484 88 01' },
  { country: 'Austria', name: 'TelefonSeelsorge', number: '142' },
  { country: 'Brazil', name: 'Centro de Valorização da Vida', number: '188' },
  { country: 'Mexico', name: 'SAPTEL', number: '800 472 7835' },
  { country: 'Argentina', name: 'Línea de Salud Mental', number: '0800-999-0091' },
  { country: 'New Zealand', name: 'Lifeline Aotearoa', number: '0800 543 354' },
  { country: 'India', name: 'AASRA', number: '+91 22 2754 6669' },
  { country: 'China', name: 'National Mental Health Helpline', number: '12320-5' },
  { country: 'Japan', name: 'TELL Lifeline', number: '03 5774 0992' },
  { country: 'South Korea', name: 'Mental Health Welfare Center', number: '1577-0199' },
  { country: 'Singapore', name: 'Samaritans of Singapore', number: '1800 221 4444' },
  { country: 'Malaysia', name: 'Befrienders KL', number: '03 7956 8145' },
  { country: 'Philippines', name: 'NCMH Crisis Hotline', number: '1553' },
  { country: 'Israel', name: 'ERAN Emotional First Aid', number: '1201' },
  { country: 'United Arab Emirates', name: 'Al Amal Mental Health', number: '800 4673' },
  { country: 'Saudi Arabia', name: 'National Center for Mental Health', number: '920033360' },
  { country: 'Iran', name: 'National Counseling Helpline', number: '1480' },
  { country: 'Lebanon', name: 'Embrace Lifeline', number: '1564' },
  { country: 'Egypt', name: 'Befrienders Cairo', number: '762 1602' },
  { country: 'South Africa', name: 'SADAG General Helpline', number: '0800 21 22 23' },
  { country: 'Kenya', name: 'Befrienders Nairobi', number: '+254 722 178 177' },
  { country: 'Nepal', name: 'National Mental Health Helpline', number: '1166' },
  { country: 'Thailand', name: 'Samaritans Thailand', number: '02 713 6793' },
  { country: 'Taiwan', name: 'Taiwan Lifeline', number: '1995' },
  { country: 'Hong Kong', name: 'Samaritan Befrienders Hong Kong', number: '2382 0000' },
  { country: 'Indonesia', name: 'Ministry of Health Hotline', number: '1500 567' },
  { country: 'Bangladesh', name: 'Kaan Pete Roi', number: '+88 09639 678 999' },
]

export const HELPLINES_BY_CC: Record<string, Helpline> = {
  AU: HELPLINES[0],
  US: HELPLINES[1],
  CA: HELPLINES[2],
  GB: HELPLINES[3],
  IE: HELPLINES[4],
  FR: HELPLINES[5],
  DE: HELPLINES[6],
  ES: HELPLINES[7],
  IT: HELPLINES[8],
  NL: HELPLINES[9],
  BE: HELPLINES[10],
  SE: HELPLINES[11],
  DK: HELPLINES[12],
  NO: HELPLINES[13],
  FI: HELPLINES[14],
  CH: HELPLINES[15],
  PL: HELPLINES[16],
  AT: HELPLINES[17],
  BR: HELPLINES[18],
  MX: HELPLINES[19],
  AR: HELPLINES[20],
  NZ: HELPLINES[21],
  IN: HELPLINES[22],
  CN: HELPLINES[23],
  JP: HELPLINES[24],
  KR: HELPLINES[25],
  SG: HELPLINES[26],
  MY: HELPLINES[27],
  PH: HELPLINES[28],
  IL: HELPLINES[29],
  AE: HELPLINES[30],
  SA: HELPLINES[31],
  IR: HELPLINES[32],
  LB: HELPLINES[33],
  EG: HELPLINES[34],
  ZA: HELPLINES[35],
  KE: HELPLINES[36],
  NP: HELPLINES[37],
  TH: HELPLINES[38],
  TW: HELPLINES[39],
  HK: HELPLINES[40],
  ID: HELPLINES[41],
  BD: HELPLINES[42],
}
