<?php
$quotes = [
    'Dorothy Parker' => [
        "Excuse my dust.",
        "And she had It. It, hell; she had Those.",
        "Salary is no object: I want only enough to keep body and soul apart.",
        "That would be a good thing for them to cut on my tombstone: Wherever she went, including here, it was against her better judgment.",
        "A lady ... with all the poise of the Sphinx though but little of her mystery.",
        "The House Beautiful is, for me, the play lousy.",
        "The ones I like ... are 'cheque' and 'enclosed.'",
        "And I'll stay away from Verlaine too; he was always chasing Rimbauds.",
        "One more drink and I'd have been under the host.",
        "It's not the tragedies that kill us; it's the messes.",
        "[On being told of Calvin Coolidge's death] How do they know?",
        "Too fucking busy, and vice versa.",
        "It serves me right for putting all my eggs in one bastard.",
        "You can lead a horticulture, but you can't make her think.",
        "What fresh hell can this be?",
        "Of course I talk to myself. I like a good speaker, and I appreciate an intelligent audience.",
        "If you don't have anything nice to say, come sit by me.",
        "Time may be a great healer, but it's a lousy beautician.",
        "Never throw mud: you can miss the target, but your hands will remain dirty.",
        "I like to have a martini/Two at the very most/After three I'm under the table/After four I'm under my host.",
        "The cure for boredom is curiosity. There is no cure for curiosity.",
        "If you want to know what God thinks about money, just look at the people He gives it to.",
        "Creativity is a wild mind and a disciplined eye.",
        "The first thing I do in the morning is brush my teeth and sharpen my tongue.",
        "If love is blind, why is lingerie so popular?",
        "The only dependable law of life - everything is always worse than you thought it was going to be.",
        "You can lead a horticulture, but you can't make her think.",
        "Years are only garments, and you either wear them with style all your life, or else you go dowdy to the grave.",
        "You can't teach an old dogma new tricks.",
        "Don't look at me in that tone of voice.",
        "Heterosexuality is not normal, it's just common.",
        "He is a writer for the ages, the ages of four to eight.",
        "A hangover is the wrath of grapes.",
        "If you wear a short enough skirt, the party will come to you.",
        "I'm not a writer with a drinking problem, I'm a drinker with a writing problem."
    ],
    'Noel Coward' => [
        "Work is much more fun than fun.",
        "I love criticism just so long as it's unqualified praise.",
        "It's discouraging to think how many people are shocked by honesty and how few by deceit.",
        "I have always paid income tax. I object only when it reaches a stage when I am threatened with having nothing left for my old age - which is due to start next Tuesday or Wednesday.",
        "Wit ought to be a glorious treat like caviar; never spread it about like marmalade.",
        "The higher the building the lower the morals.",
        "I like long walks, especially when they are taken by people who annoy me.",
        "My body has certainly wandered a good deal, but I have an uneasy suspicion that my mind has not wandered enough.",
        "Time has convinced me of one thing: Television is for appearing on - not for looking at.",
        "Just say the lines and don't trip over the furniture.",
        "Success took me to her bosom like a maternal boa constrictor.",
        "There's always something fishy about the French.",
        "People are wrong when they say that the opera is not what it used to be. It is what it used to be. That's what's wrong with it.",
        "I have a memory like an elephant. In fact, elephants often consult me.",
        "Mad dogs and Englishmen go out in the midday sun.",
        "Why do I drink champagne for breakfast? Doesn't everyone?",
        "Thousands of people have talent. I might as well congratulate you for having eyes in your head. The one and only thing that counts is: Do you have staying power?",
        "I'm not a heavy drinker, I can sometimes go for hours without touching a drop.",
        "The customer is always wrong.",
        "Extraordinary how potent cheap music is."
    ],
    'Winston Churchill' => [
        "Success is not final, failure is not fatal: It is the courage to continue that counts.",
        "History will be kind to me for I intend to write it.",
        "If you are going through hell, keep going.",
        "You have enemies? Good. That means you've stood up for something, sometime in your life.",
        "Courage is what it takes to stand up and speak; courage is also what it takes to sit down and listen.",
        "To improve is to change; to be perfect is to change often.",
        "Never, never, never give in except to convictions of honor and good sense.",
        "A pessimist sees the difficulty in every opportunity; an optimist sees the opportunity in every difficulty.",
        "We make a living by what we get, but we make a life by what we give.",
        "Democracy is the worst form of government, except for all the others.",
        "The price of greatness is responsibility.",
        "A lie gets halfway around the world before the truth has a chance to get its pants on.",
        "Kites rise highest against the wind, not with it.",
        "The best argument against democracy is a five-minute conversation with the average voter.",
        "I am fond of pigs. Dogs look up to us. Cats look down on us. Pigs treat us as equals.",
        "In the course of my life, I have often had to eat my words, and I must confess that I have always found it a wholesome diet.'",
        "Never in the field of human conflict was so much owed by so many to so few.",
        "You can always count on the Americans to do the right thing after they have tried everything else.",
        "We are masters of the unsaid words, but slaves of those we let slip out.",
        "Success consists of going from failure to failure without loss of enthusiasm."
    ],
    'Eleanor Roosevelt' => [
        "No one can make you feel inferior without your consent.",
        "A woman is like a tea bag; you never know how strong it is until it's in hot water.",
        "Do one thing every day that scares you.",
        "The future belongs to those who believe in the beauty of their dreams.",
        "Great minds discuss ideas; average minds discuss events; small minds discuss people.",
        "You must do the things you think you cannot do.",
        "With the new day comes new strength and new thoughts.",
        "It is better to light a candle than curse the darkness.",
        "The purpose of life is to live it, to taste experience to the utmost, to reach out eagerly and without fear for newer and richer experience.",
        "You gain strength, courage, and confidence by every experience in which you really stop to look fear in the face.",
        "Life is what you make it. Always has been, always will be.",
        "Happiness is not a goal; it is a by-product.",
        "It isn't enough to talk about peace. One must believe in it. And it isn't enough to believe in it. One must work at it.",
        "Justice cannot be for one side alone, but must be for both.",
        "The giving of love is an education in itself.",
        "Learn from the mistakes of others. You can't live long enough to make them all yourself.",
        "Friendship with oneself is all-important because without it one cannot be friends with anyone else in the world.",
        "Never allow a person to tell you no who doesn't have the power to say yes.",
        "Women are like teabags. We don't know our true strength until we are in hot water!",
        "I could not, at any age, be content to take my place by the fireside and simply look on. Life was meant to be lived."
    ],
    'Harpo Marx' => [
        "Harpo, look at me when I'm talking to you!",
        "Honk! Honk!",
        "I was so dumb they had to burn the school down to get me out.",
        "I don't want to be remembered. I want the nice words when I can hear them.",
        "In Hollywood, brides keep the bouquets and throw away the groom.",
        "My one regret in life is that I am not someone else.",
        "I am the most fortunate self-taught harpist and non-speaking actor who has ever lived.",
        "I played the harp in public for the first time, and things have been going downhill ever since.",
        "I was the same kind of father as I was a harpist. I played by ear.",
        "If things get too much for you and you feel the whole world is against you, go stand on your head. If you can think of anything crazier to do, do it.",
        "Humor is the truth; wit is an exaggeration of the truth.",
        "Silent comedy too, is a timeless art.",
        "I never got the hang of speaking. I think I was traumatized into silence by my brothers.",
        "I'd rather be silent and funny, than loud and unfunny.",
        "Remember, if you ever need a helping hand, you'll find one at the end of your arm.",
        "If I can make people smile, then I have served my purpose for God.",
        "No one is ever really alone. You are part of everything alive.",
        "I've been chased by women I never even met.",
        "I must admit, I was born at a very early age.",
        "Every day is a gift, that's why they call it the present."
    ],
    'Dale Carnegie' => [
        "Remember, happiness doesn't depend upon who you are or what you have; it depends solely upon what you think.",
        "Most of the important things in the world have been accomplished by people who have kept on trying when there seemed to be no hope at all.",
        "You can make more friends in two months by becoming interested in other people than you can in two years by trying to get other people interested in you.",
        "Develop success from failures. Discouragement and failure are two of the surest stepping stones to success.",
        "It isn't what you have or who you are or where you are or what you are doing that makes you happy or unhappy. It is what you think about it.",
        "People rarely succeed unless they have fun in what they are doing.",
        "Success is getting what you want. Happiness is wanting what you get.",
        "Any fool can criticize, condemn, and complain but it takes character and self control to be understanding and forgiving.",
        "The person who seeks all their applause from outside has their happiness in another's keeping.",
        "Do the hard jobs first. The easy jobs will take care of themselves.",
        "When dealing with people, remember you are not dealing with creatures of logic, but creatures of emotion.",
        "If you want to be enthusiastic, act enthusiastic.",
        "Don't be afraid of enemies who attack you. Be afraid of the friends who flatter you.",
        "All men have fears, but the brave put down their fears and go forward, sometimes to death, but always to victory.",
        "Talk to someone about themselves and they'll listen for hours.",
        "The only way to get the best of an argument is to avoid it.",
        "Any fool can criticize, condemn, and complain - and most fools do.",
        "Actions speak louder than words, and a smile says, 'I like you. You make me happy. I am glad to see you.'",
        "Names are the sweetest and most important sound in any language.",
        "Happiness doesn't depend on any external conditions, it is governed by our mental attitude."
    ],
    'Terry Pratchett' => [
        "In ancient times cats were worshipped as gods; they have not forgotten this.",
        "The trouble with having an open mind, of course, is that people will insist on coming along and trying to put things in it.",
        "Wisdom comes from experience. Experience is often a result of lack of wisdom.",
        "So much universe, and so little time.",
        "The truth may be out there, but lies are inside your head.",
        "Do you not know that a man is not dead while his name is still spoken?",
        "Stories of imagination tend to upset those without one.",
        "It's still magic even if you know how it's done.",
        "Real stupidity beats artificial intelligence every time.",
        "Evil begins when you begin to treat people as things.",
        "Time is a drug. Too much of it kills you.",
        "I'll be more enthusiastic about encouraging thinking outside the box when there's evidence of any thinking going on inside it.",
        "Five exclamation marks, the sure sign of an insane mind.",
        "In the beginning there was nothing, which exploded.",
        "Humans need fantasy to be human. To be the place where the falling angel meets the rising ape.",
        "If cats looked like frogs we'd realize what nasty, cruel little bastards they are. Style. That's what people remember.",
        "Sometimes it is better to light a flamethrower than curse the darkness.",
        "There are times in life when people must know when not to let go. Balloons are designed to teach small children this.",
        "Always be wary of any helpful item that weighs less than its operating manual.",
        "A lie can run round the world before the truth has got its boots on."
    ],
    'Blackadder' => [
        "I have a plan so cunning you could put a tail on it and call it a weasel.",
        "Baldrick, your head is as empty as a eunuch’s underpants.",
        "We are in the stickiest situation since Sticky the Stick Insect got stuck on a sticky bun.",
        "Percy, far from being a fit consort for a prince of the realm, you would bore the leggings off a village idiot.",
        "Witchsmeller Pursuivant: I shall send a letter to the Times! Blackadder: [sarcastically] Oh, frightfully scary! I shall have to get my men to change their underpants.",
        "As cunning as a fox who's just been appointed Professor of Cunning at Oxford University?",
        "You ride a horse rather less well than another horse would.",
        "Baldrick, I would like to say how much I will miss your honest, friendly companionship. But as we both know, it would be an utter lie.",
        "I do feel, sir, that any anti-Baldric feelings I may have expressed in the past have now been totally assuaged.",
        "It's a ghastly mess, Lord Blackadder, and something's got to be done! I want to be young and wild, and then middle-aged and rich, and then old and annoy people by pretending that I'm deaf.",
        "Baldrick, have you no idea what irony is? Baldrick: Yeah, it's like goldy and bronzy only it's made out of iron.",
        "The path of my life is strewn with cowpats from the devil's own satanic herd!",
        "To you, Baldrick, the Renaissance was just something that happened to other people, wasn't it?",
        "Trust me to be lumbered with a Baldrick whose great ambition in life is to own something that might vaguely be considered a potato.",
        "Madam, life without you is like a broken pencil... pointless.",
        "I fear the words 'I have a cunning plan' are rapidly marching towards this conversation with ill-deserved confidence.",
        "The eyes are open, the mouth moves, but Mr. Brain has long since departed, hasn't he, Percy?",
        "Fortune vomits on my eiderdown once more.",
        "Baldrick, does it have to be this way? Our valued friendship ending with me cutting you into long strips and telling the prince that you walked over a very sharp cattle grid in an extremely heavy hat?",
        "Right Baldrick, let's try again, shall we? This is called adding. If I have two beans, and then I add two more, what do I have? Baldrick: Some beans."
    ]
];

// Select a random author
$randomAuthor = array_rand($quotes);

// Select a random quote from the chosen author's array
$randomQuote = $quotes[$randomAuthor][array_rand($quotes[$randomAuthor])];

// Echo the quote with the author
echo "\"$randomQuote\" - $randomAuthor";
?>